name: Environment workflow run

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to deploy to
        type: choice
        options:
          - development
          - production
          - DevOps

jobs:
  deploy:
    runs-on: self-hosted  
    if: github.event.inputs.environment != 'development' 
    steps:
      - name: 'Run_java'
        run: echo "the workflow is running"
