name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to deploy to
        type: choice
        options:
          - development
          - Devops
          - production
jobs:
  build:
    runs-on: self-hosted
    environment: ${{ github.event.inputs.environment }}
   
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
  deploy:
    runs-on: self-hosted
    #needs: build

    steps:
    - name: Deploy to Server
      run: |
        Copy-Item target\*.war "C:\Host\Apache Software Foundation\Tomcat 10.1.25\webapps"
