name: My Matrix Workflow

on:
  push:
    branches: [main]

jobs:
  my_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Development, Production, DevOps]
    steps:
      - uses: actions/checkout@v3
      - name: Set environment
        run: echo "Environment:${{ matrix.environment }}"
      - name: Run task
        run: |
          if [[ "${{ matrix.environment }}" == "Development" ]]; then
          elif [[ "${{ matrix.environment }}" == "Production" ]]; then
          elif [[ "${{ matrix.environment }}" == "DevOps" ]]; then
          fi
