name: My Matrix sequential Workflow

on:
 workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  job_development:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        environment: [Development]
    steps:
      - name: Set environment
        run: echo "Environment:${{ matrix.environment }}"
      - name: Run Development tasks
        run: echo "Running tasks for Development"

  job_production:
    runs-on: ubuntu-latest
    needs: job_development
    strategy:
      matrix:
        environment: [Production]
    steps:
      - name: Set environment
        run: echo "Environment:${{ matrix.environment }}"
      - name: Run Production tasks
        run: echo "Running tasks for Production"

  job_devops:
    runs-on: ubuntu-latest
    needs: job_production
    strategy:
      matrix:
        environment: [DevOps]
    steps:
      - name: Set environment
        run: echo "Environment:${{ matrix.environment }}"
      - name: Run DevOps tasks
        run: echo "Running tasks for DevOps"
