name: Generate Table

on:
  push:
    branches: [main]

jobs:
  generate_table:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate data
        run: # This line is a comment (not a command)
          data=[
            ["Column 1", "Column 2", "Column 3"],
            ["Value 1", "Value 2", "Value 3"],
            ["Value 4", "Value 5", "Value 6"]
            ]
      - name: Print table
        run: |
          echo "| Column 1 | Column 2 | Column 3 |"
          echo "|---|---|---|"
          for row in "${data[@]}"; do
            echo "| ${row[@]} |"
          done
