name: Generate Table

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate table
      id: generate_table
      run: |
        echo "| Column 1 | Column 2 | Column 3 | Column 4 | Column 5 | Column 6 | Column 7 |" >> table.md
        echo "|----------|----------|----------|----------|----------|----------|----------|" >> table.md
        echo "| Test 1   | Test 2   | Test 3   | Test 4   | Test 5   | Test 6   | Test 7   |" >> table.md
        echo "| Test 8   | Test 9   | Test 10  | Test 11  | Test 12  | Test 13  | Test 14  |" >> table.md
        cat table.md

    - name: Set output 
      id: set_output
      run: |
        echo "table<<EOF" >> $GITHUB_ENV
        cat table.md >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    - name: Display table
      run: echo "${{ env.table }}"


