name: check the deploy run
on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to deploy to
        type: choice
        options:
          - development
          - Devops
          - production
jobs:
  build:
    runs-on: self-hosted
    environment: ${{ github.event.inputs.environment }}


deploy:
    runs-on: self-hosted
    #needs: build

    steps:
    - name: Deploy to Server
      run: |
        Copy-Item target\*.war "C:\Host\Apache Software Foundation\Tomcat 10.1.25\webapps"
