name: check the workflow run

on:
  workflow_run:
    workflows: [Java CI with Maven]
    types: [completed]

jobs:
  download:
    runs-on: self-hosted
    environment: DevOps
    steps:
      - name: 'Run_java'
        run: echo "the workflow is running"
